"""rename tag to name

Revision ID: 79e9c8deac8b
Revises: b4681a7086da
Create Date: 2020-01-19 23:01:49.494678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79e9c8deac8b'
down_revision = 'b4681a7086da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(length=128), nullable=False))
    op.drop_index('tag', table_name='tags')
    op.create_unique_constraint(None, 'tags', ['name'])
    op.drop_column('tags', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag', mysql.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_index('tag', 'tags', ['tag'], unique=True)
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
