"""add ingredient tags

Revision ID: b4681a7086da
Revises: d0a5d408fb45
Create Date: 2020-01-18 15:06:03.156505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4681a7086da'
down_revision = 'd0a5d408fb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingredients_id', sa.BigInteger(), nullable=False),
    sa.Column('tags_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ingredients_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_tags')
    # ### end Alembic commands ###
