""" make unique

Revision ID: d0a5d408fb45
Revises: 8f01da7a9b8c
Create Date: 2020-01-18 13:18:40.019663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a5d408fb45'
down_revision = '8f01da7a9b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'glassware', ['name'])
    op.create_unique_constraint(None, 'ingredients', ['name'])
    op.create_unique_constraint(None, 'tags', ['tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'ingredients', type_='unique')
    op.drop_constraint(None, 'glassware', type_='unique')
    # ### end Alembic commands ###
