"""Add initial Recipe tables

Revision ID: 8f01da7a9b8c
Revises: 
Create Date: 2020-01-14 00:09:13.483259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f01da7a9b8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'glassware',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('image', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'ingredients',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('image', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'tags',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('tag', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'recipes',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('desc', sa.Text(), nullable=True),
        sa.Column('instructions', sa.Text(), nullable=True),
        sa.Column('image', sa.String(length=128), nullable=True),
        sa.Column('glassware_id', sa.BigInteger(), nullable=False),
        sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['glassware_id'], ['glassware.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'recipe_ingredients',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('recipes_id', sa.BigInteger(), nullable=False),
        sa.Column('ingredients_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['ingredients_id'], ['ingredients.id'], ),
        sa.ForeignKeyConstraint(['recipes_id'], ['recipes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'recipe_tags',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('recipes_id', sa.BigInteger(), nullable=False),
        sa.Column('tags_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(['recipes_id'], ['recipes.id'], ),
        sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tags')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipes')
    op.drop_table('tags')
    op.drop_table('ingredients')
    op.drop_table('glassware')
    # ### end Alembic commands ###
